name: 'build asciidoctor action'
author: 'Tony Vattathil'
description: 'asciidoctor Build action'
branding:
  icon: 'file'
  color: 'green'
inputs:
  program:
    description: 'asciidoctor'
    required: true
    default: 'asciidoctor -r asciidoctor-diagram index.adoc'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.program }}
outputs:
  time:
    description: 'Action Completed'
